version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-none}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]
    restart: always

  model-loader:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
      curl -X POST http://ollama:11434/api/pull
      -H 'Content-Type: application/json'
      -d '{\"name\": \"llama3\"}'"
    restart: "no"

  deep-seek-model-loader:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    entrypoint: /bin/sh
    command: >
      -c "sleep 5 && curl -X POST http://ollama:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"deepseek-r1:7b\"}'"
    restart: "no"

  backend:
    container_name: backend
    #build: ./backend
    image: azou2020/backend:v2.1
    # platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=deepseek-r1:7b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    #   args:
    #     VITE_CHAT_API_URL: http://backend:8000/chat
    image: azou2020/frontend:v3
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  ollama-data:
