version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: always

  model-loader:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
      curl -X POST http://ollama:11434/api/pull
      -H 'Content-Type: application/json'
      -d '{\"name\": \"llama3\"}'"
    restart: "no"
  ee-cloud:
    # build: ./cloud
    container_name: backend-server
    image: azou2020/ee-cloud:v1
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama3
    restart: always

volumes:
  ollama-data:
